---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: services
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: registry.gitlab.com/4lambda/web:v3.0.0c
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
